nuggylib/minecraft-asset-reader

package-lock.json
src/CLIApp.tsx
src/components/shared/Menu.tsx

After updating to functional components and Hooks, a bug was introduced where the menu wouldn't render the appropriate options after selecting the "Bootstrap" option. 
This PR fixes that bug.
1. Always set the selected option now (so that the state changes, and we have something to revert on succesful data parse)
2. De-select the selected option once data parse is complete
Menu renders options post-bootstrap successfully! :tada:

Menu render fix after bootstrapping data

---

package-lock.json
package.json
src/CLIApp.tsx
src/hooks/useMenuOptions.tsx
src/hooks/useParsedData.tsx
test/hooks/useMenuOptions.test.ts

Add tests for `useMenuOption` custom Hook.
* Tests for `useMenuOption` Hook
* Bug fix for `useMenuOption`; prevents unnecessary re-renders (was previously updating with _any_ change to the larger data objects; we just needed to check for existence in the dependencies)

Tests for useMenuOptions Hook

---

.husky/pre-commit
package.json
test/hooks/useMenuOptions.test.ts

* Run tests instead of `lint:commit` (should rename this later)
* `lint:commit` was leading to further changes that also needed to be committed, and the subsequent husky hook event may trigger yet more changes (in some cases, I had 2 extra commits just to get one change committed)
* Fix tests

Make husky less annoying

---

src/api/raw-data/getBlocksForNamespace.ts
src/services/core/cache/index.ts

Endpoint to get blocks for namespace now supports a `sort` parameter. Technically `ascending` is a supported value, but nothing changes with the logic.
When `sort=descending`, the block pages are reversed (descending order).

Support for getting blocks in descending order

---

src/api/raw-data/getBlocksForNamespace.ts
src/services/core/cache/index.ts

The `raw-data/blocks` endpoint now accepts an optional parameter, `q`. Pass a search string through this variable to filter the blocks by the given string.

Search blocks by string

---

.gitignore
src/services/core/server/server.ts

Enables self-hosting the Minecraft Asset Reader webapp.
This will not work without first:
1. Build the webapp > copy the `build` directory
2. Paste the `build` directory at the `minecraft-asset-reader` directory
Once you've copied the `build` directory over, you will be able to access it by navigating to `localhost:3000` in the browser. The `build` directory SHOULD NOT be committed; we need to set up a build pipeline later that will handle this for us (probably in a slightly-different setup as well).

Config for self-hosted web app

---

packages/client/src/BlockModal.tsx

The state would not accurately-reflect the selected values for cached blocks. This PR fixes the issue by updating the `value` so that the `blocks/` portion of the name is excluded when setting the value for the dropdown options.

Fix dropdown statefulness

---

packages/client/src/BlockModal.tsx
packages/client/src/BlockModalNumberInput.tsx

Adds new fields to the block config modal; back end needs to be wired up, still.
Example screenshot of changes

New fields on block config modal

---

packages/client/src/components/block-modal/BlockModal.tsx

Just adds the fields and some rudimentary enable/disable logic based on some conditions. These conditions are not arbitrary, but based on how the game functions.
This does not yet implement the back end portion of this code. However, it seems like it may be easier to manage this app with a persistent data store. That will likely come before the backend API needed for this logic is updated.

Block harvest data config fields

---

packages/cli/src/api/content-map/UPDATED/addOrUpdateBlock.ts
packages/cli/src/api/content-map/UPDATED/getBlocks.ts
packages/cli/src/api/content-map/UPDATED/getHarvestToolQualities.ts
packages/cli/src/api/content-map/UPDATED/getHarvestTools.ts
packages/cli/src/services/core/server/server.ts
packages/cli/src/services/db/index.ts

Adds two new endpoints:
1. `/harvest-tool`
2. `/harvest-tool/quality`
Both of these endpoints are extremely simple GET endpoints; no parameters are required since the data set is always small; simply work with the resulting data set.
* `GET` to `http://localhost:3000/harvest-tool`
* `GET` to `http://localhost:3000/harvest-tool/quality`
Harvest tool response:
```
[
{
"id": 1,
"key": "axe"
},
{
"id": 2,
"key": "hoe"
},
{
"id": 3,
"key": "pickaxe"
},
{
"id": 4,
"key": "shovel"
},
{
"id": 5,
"key": "hand"
},
{
"id": 6,
"key": "none"
}
]
```
Harvest tool quality response:
```
[
{
"id": 1,
"key": "wood"
},
{
"id": 2,
"key": "stone"
},
{
"id": 3,
"key": "iron"
},
{
"id": 4,
"key": "gold"
},
{
"id": 5,
"key": "diamond"
},
{
"id": 6,
"key": "netherite"
},
{
"id": 7,
"key": "none"
}
]
```

Get harvest tool/qualities endpoints

---

packages/cli/src/api/content-map/UPDATED/deleteBlock.ts
packages/cli/src/services/core/server/server.ts
packages/cli/src/services/db/index.ts

Delete a _configured_ block. Note that there is no way to delete blocks from the "raw data" map; we don't want to remove those since those serve as the "raw list" that the user selects and configures blocks from.
**The database implementation will replace the Content Map ONLY - the raw data format will stay the same**
* `DELETE` to `http://localhost:3000/block?key=test`
* Where `test` is the key value for the block being deleted
```
{
"stmt": {},
"lastID": 0,
"changes": 1
}
```
* Note the `changes` value - indicates how many rows were changed
```
{
"stmt": {},
"lastID": 0,
"changes": 0
}
```

Delete block endpoint

---

packages/cli/src/api/content-map/UPDATED/addOrUpdateBlock.ts
packages/cli/src/api/content-map/UPDATED/deleteBlock.ts
packages/cli/src/api/content-map/UPDATED/getBlocks.ts
packages/cli/src/api/content-map/UPDATED/getHarvestToolQualities.ts
packages/cli/src/api/content-map/UPDATED/getHarvestTools.ts
packages/cli/src/main.tsx
packages/cli/src/services/core/cache/index.ts
packages/cli/src/services/core/components/SetAssetsPathForm.tsx
packages/cli/src/services/db/index.ts

Now, instead of an app-specific database, the _app creates a database_ for the user once they provide a valid path to the assets directory. This allows us to persist separate "instances" of data; for example, if a user has multiple mods to configure, this implementation makes sure that each mod's data stays separate.
* Database creation is deferred until a valid assets path has been submitted
* Each existing database-connected API now requires an additional parameter, `gameVersion`
* _This allows the application to serve up persisted data from previous sessions, despite the cached data only being specific to the currently-imported game version; in other words, the web app will only ever show the currently-imported game version, but you can query for data from **any** game version that …

Game version specific SQLite databases

---

packages/cli/src/main.tsx
packages/cli/src/services/core/components/SetAssetsPathForm.tsx
packages/cli/src/services/core/server/server.ts
packages/cli/src/services/db/index.ts

All db-linked mutations now return data in the shape of a `MutationResult`, which contains:
* `success` - whether or not the mutation operation happened as expected
* `message` - an optional message describing the return value (this is useful when returning error text to the caller)

Unify return values for mutations

---

packages/cli/src/api/content-map/UPDATED/addNamespace.ts
packages/cli/src/api/content-map/UPDATED/addOrUpdateBlock.ts
packages/cli/src/api/content-map/UPDATED/getNamespaces.ts
packages/cli/src/services/core/server/server.ts
packages/cli/src/services/db/index.ts
packages/cli/src/services/db/mutations/createTables.ts

Adds two new APIs:
* `GET` - `/imported/namespace` - gets a list of all stored namespaces in the specified game version DB
* `POST` - `/imported/namespace` - create a new namespace; this endpoint is intended to be used when the user selects a namespace to in which to configure content (e.g., blocks, items, recipes, etc)
Both APIs require the `gameVersion` parameter; for the `POST` endpoint, include it as an additional `body` parameter. For the `GET` endpoint, it's just a query parameter.

Add and get namespaces APIs

---

package.json
packages/cli/src/api/content-map/UPDATED/addOrUpdateBlock.ts
packages/cli/src/api/content-map/UPDATED/getNamespaces.ts
packages/cli/src/services/core/server/server.ts
packages/cli/src/services/db/index.ts
packages/cli/src/services/db/mutations/createTables.ts
packages/cli/src/services/minecraft/minecraftBlockRenderer.ts
packages/cli/src/types/shared.ts
packages/client/src/components/block-modal/BlockModal.tsx
packages/client/src/index.tsx
yarn.lock

This PR connects the Block Modal to the database by saving the configured fields to the database when the user clicks "Save". This is technically still making calls to the cache, _but caching is broken for the BlockModal after this PR_. I didn't want to spend time debugging the cache implementation, which will no longer be responsible for handling "configured" data (but will still be used for raw data).
1. Start the CLI > provide a valid assets path
2. Start the web app > configure a block > _click save_ (this is what actually "commits" the data to the database)
> At the time of writing this PR, the only fields that will be **set** are `id`, `key`, `title` (if the user set a value for it), and `icon`; the remaining fields are not yet in use.
To test that the block data was generated as …

Add block to db on save

---

packages/cli/src/services/db/index.ts
packages/client/src/components/block-modal/BlockModal.tsx

Previously, I had just slapped in some code that simply replaced records with new data while I sorted out other more-pressing matters.
Now, the `addOrUpdateBlock` method actually updates existing records instead of replacing the block record (and therefore replacing the block's ID - no bueno).
This PR also completely unlinks the save logic from the cache - now, when you click save in the block modal, it _only_ saves the data to the database; nothing gets placed in the cache.

Upsert logic for adding blocks

---

packages/client/src/components/block-modal/BlockModal.tsx

`BlockModal` is no longer linked to the cache. Now the block data is loaded in using an API that is linked to the database.
1. Start the CLI app > specify the assets directory
2. Start the webapp > configure a block (the `BlockModal` is what renders when you click on a given block card in the list grid)
3. Save the configured block > open the same block again > the Title field should be set to whatever you saved it as before

Load data for BlockModal from DB

---

packages/cli/src/api/session/getCachedGameVersion.ts
packages/cli/src/services/core/cache/index.ts
packages/cli/src/services/core/server/server.ts
packages/cli/src/services/minecraft/minecraftUtility.ts
packages/client/src/components/block-modal/BlockModal.tsx

Add an API to get the cached game version. The cached game version is set once the raw data has been successfully read in.
The `BlockModal` component now uses the new endpoint to load in the cached game version so it knows which database it should load from/save to.
You should be able to configure a block in the web app as usual, and the saved block title should populate the title field for configured blocks in the `BlockModal`

Get (and use) cached game version

---

package.json
packages/cli/src/api/persistence/addOrUpdateBlock.ts
packages/cli/src/api/persistence/getHarvestToolQualitiesForBlock.ts
packages/cli/src/api/persistence/getHarvestToolsForBlock.ts
packages/cli/src/services/core/server/server.ts
packages/cli/src/services/db/index.ts
packages/cli/src/services/db/mutations/createTables.ts
packages/cli/src/types/shared.ts
packages/client/src/components/block-modal/BlockModal.tsx
packages/client/src/hooks/useCachedGameVersion.ts

Complete the `BlockModal` by implementing to configure and save the harvest tool (and quality) for any given block. 
* `reset-db` script to reset the database
* `yarn reset-db` at the project root - at the time of writing, this will only work on Unix systems - it will crap out on Windows, though we do intend to support this later
* `addOrUpdateBlock` API now handles two additional parameters:
1. `harvestTool` - _Optional_ - `string` - The optimal tool to use for harvesting the given block
2. `harvestToolQualities` - _Optional_ - `string[]` - The list of qualities for the harvest tool that can be used to harvest the block (e.g., Obsidian needs a pickaxe of _diamond_ quality, or better, to be harvested)
* New API endpoints (see below)
* Several database operations to facilitate the new …

Complete block config

---

packages/cli/src/services/core/cache/index.ts
packages/cli/src/services/core/exporter.ts
packages/cli/src/services/db/index.ts
packages/cli/src/services/minecraft/minecraftBlockRenderer.ts
packages/client/src/components/Sidebar.tsx

Remove the (confusing-as-hell) content map and instead use the database, now that we have one, when exporting to Sanity!
For now, we are also disabling exporting to the local file system since that logic was written when the project had a completely different structure; the logic doesn't appear to be that relevant any longer (any references to code that used the "`generated`" directory probably also needs to be removed/updated)
* Disable File system export (the option is still in the GUI, but it's a no-op - the code has been commented out)
* Make export-to-Sanity logic use the database instead of the Content map
* This is a necessary update as the content map is no longer used; all configured game data is stored in a game-version specific SQLite database
* Update the image scaling logic …

Make export use DB data

---

packages/cli/src/CLIApp.tsx
packages/cli/src/components/hooks/useMenuOptions.tsx
packages/cli/src/minecraft/minecraftUtility.ts
packages/cli/src/services/core/components/SetMinecraftVersion.tsx
packages/cli/src/utils/checkForDefaultAssetsDir.ts
packages/cli/src/utils/checkForJar.ts
packages/cli/src/utils/detectLocalVersions.ts
packages/cli/src/utils/extractJar.ts
packages/cli/src/utils/index.ts

See issue #73 
Add the logic and components required to support a "default path" flow where the user is able to select "use default path" instead of manually entering the Minecraft assets directory. 
Once the user selects the "use default path" option, the minecraft-asset-reader tool will check the default installation directory (for the user's operating system) for Minecraft installations. If it finds one or more, it will list them as options. The user can then select one of the options. 
- If the Minecraft installation directory only has `.jar` files, the tool will extract the `.jar` files. 
- If a Minecraft assets directory namespace doesn't have a recognized directory structure, the tool will skip it during the asset import. An example of such a scenario is the `realms` namespace in …

Add default path flow

---

packages/cli/src/CLIApp.tsx
packages/cli/src/components/SetMinecraftVersion.tsx

Move `SetMinecraftVersion` to the new location (seems like some weirdness happened on a previous merge conflict). Additionally, prevent setting state when component is unmounted.

Move SetMinecraftVersion to components

---

README.md

Remove stale Readme instructions and add directions on the complete workflow using the Sanity starter template.

Sanity starter instructions in Readme

---

packages/cli/src/api/persistence/addOrUpdateBlock.ts
packages/cli/src/db/index.ts
packages/cli/src/db/mutations/createTables.ts
packages/client/src/components/block-modal/BlockModal.tsx

We were previously exposing a "description" field in the Block modal. The idea was to provide the user with a way to set some description text to start with. However, given that the schema for the `description` field in the `minecraftBlock` type of the Minecraft Blog Starter is _NOT_ a simple text field, but rather an array of text blocks, it seems much easier to simply drop the description field on our end entirely and rely on Sanity for the content-heavy fields such as this one.
Since the end goal of this entire project is to make it easier for the user to _create_ the site starter content (not "maintain" it), we should opt to expose "data" fields on our end, and leave the more subjective ones up to Sanity as text blocks (or some other form of rich content).

Remove block description field

---

package.json
packages/cli/package.json
packages/cli/src/cache/index.ts
packages/cli/src/minecraft/minecraftBlockRenderer.ts

We used to create a generated directory as a temporary location to hold images. This was one of those "quick and dirty" solutions we implemented just to see the icon generation logic. Since we have long since gotten past that point, it's time to remove the generated directory logic.

Remove generated directory logic

---

packages/cli/src/CLIApp.tsx
packages/cli/src/components/hooks/useMenuOptions.tsx

Now that we have a way to build the entire app, we can start serving up the built webapp code. This is _technically_ also possible to do with the TypeScript code, but I'd rather not slap the `build` directory into the source code area. It seems much cleaner to just keep all of the built code together.
With that said, if you run `yarn build-app`, then `yarn run-app`, you'll see a new menu option, `Open webapp`, which simply opens a browser tab on the webapp (`http://localhost:3000/`)
This pretty much rounds out the full end-to-end functionality of the app. All that's left now is to make it run as a standalone CLI. We obviously have much more in the way of features, but the core architecture for this application is reaching a good final "Version 1" (or more-likely, a beta... :sweat_smile: ) …

Expose link to webapp in built code

---

README.md
package.json
packages/client/src/components/ExportConfirmationModal.tsx
packages/client/src/constants.ts
packages/client/yarn.lock
yarn.lock

Remove FS as an export option as it wasn't really useful. For now, only Sanity will be supported (though, it will be easy to add support for any other vendor we want).
Going forward, when adding support for a vendor, **make sure they support the ability to manage the schema from the API**. Sanity is an exception to this rule only because we have previous experience with Sanity. We had to make a custom starter template in order to actually support Sanity, and I'd rather not have to do that for every provider.
* Note in Readme about PostCSS vulnerability issue
* `yarn reset`
* Command to delete `dist`, `out`, project `node_modules` and all package `node_modules` directories and reinstall all dependencies
* Use this when:
* _You've just started on a new branch and want to ensure everything …

Remove FS as export option

---

README.md
packages/cli/src/CLIApp.tsx

Prevent duplicate tab from opening when clicking "open webapp" menu option.
This happened because the callback to `open` was triggering an additional render cycle, during which, the selected menu option was still `OPEN_WEBAPP`. This caused the `open` logic to be run exactly twice:
* **First time**: The "expected" open call
* **Second time**: The "extra" open call, triggered by the callback to `open`
* This would not trigger a third rendering because, by running the logic of the callback, the menu option was de-selected by `clearSelectedOptionHandler`
* Though this technically does trigger another render cycle, it won't lead to an additional tab being opened because, in the third run, the selected menu option is `null`
* Fix to prevent opening duplicate webapp tab
* Information regarding …

Prevent duplicate webapp tab from opening

---

packages/cli/src/api/site-data/exportToSanity.ts
packages/cli/src/exporter.ts
packages/client/src/components/ExportConfirmationModal.tsx

No longer bother with handling multiple scale image sizes on export (Sanity API has a way to scale images hosted on their platform - use that :+1: )
* Simplify export modal to just have Sanity export details
* Default to using only one scale size when exporting to sanity (`22`x)

Only use one scale size when exporting to Sanity

---

package.json
packages/cli/src/db/mutations/createTables.ts
packages/cli/src/exporter.ts
packages/client/src/components/block-modal/BlockModal.tsx

Make tool and qualities required when configuring them, and upload them to Sanity on export.
* `yarn clear-db` command - simply deletes all DB data (useful anytime you make a change to the DB schema)
* Pass harvest tool and qualities to Sanity on upload
* Make Block modal save button disabled when harvest tool and qualities are unset

Enforce required fields for blocks
